service: mail
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: sa-east-1
  timeout: 15

functions:
  api:
    handler: src/rest/mail.handler
    events:
      - httpApi: '*'
      - httpApi: 
          method: 'POST'
          path:  '/api/v1/mails'
          description: 'Send Mail'
          summary: 'Send Mail'
          bodyType: 'IMail'
          swaggerTags: ['Mail Resources']
          responseData:
            200:
              description: 'Sucessfully Send charge'
              bodyType: 'IServiceResponse'
            500:
              description: 'Internal Server Error'
              bodyType: 'IServiceResponse'

plugins:
  - serverless-auto-swagger
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

useDotenv: true

custom:
  autoswagger:
    useStage: false
    title: 'Mail'
    description: 'Doocumentation for Mail API'
    version: '1.0.0'
    swaggerPath: '/api/v1/docs'
    typefiles: ['./src/model/mail.model.ts', './src/model/service-response.model.ts']
