// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "mail",
    "version": "1"
  },
  "paths": {},
  "definitions": {
    "Mail": {
      "properties": {
        "subject": {
          "title": "Mail.subject",
          "type": "string"
        },
        "body": {
          "title": "Mail.body",
          "type": "string"
        },
        "recipients": {
          "items": {
            "title": "Mail.recipients.[]",
            "type": "string"
          },
          "title": "Mail.recipients",
          "type": "array"
        }
      },
      "required": [
        "subject",
        "body",
        "recipients"
      ],
      "additionalProperties": false,
      "title": "Mail",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};